### ISSUE TITLE
FileNotFoundError in nmap scan.

### ISSUE THREAD

**Issue by holmes-py** [dievus/threader3000#5]
![image](https://user-images.githubusercontent.com/54495695/88223246-c620a900-cc84-11ea-94f3-3f7a91b1ddbf.png)

System: Arch Linux
Nmap: Installed.
IP that it ran on: localhost
Option selected: 1

**Comment by holmes-py** [comment]
Also, while scanning for localhost (i.e. Empty enter), It should show Scanning Target as 127.0.0.1, and not 0.0.0.0.
Not sure if that's intended.

**Comment by dievus** [comment]
I've just checked this on a Raspberry Pi, Windows, Kali, and a Ubuntu machine (I have a local server), to which none of them gave me this error.  Simply pressing the enter button rather than an actual IP address causes the error you have used, and that is because of Python3 and it's limitations, not because of the program.  

------------------------------------------------------------
        Threader 3000 - Multi-threaded Port Scanner          
                       Version 1.0.6                    
                   A project by The Mayor               
------------------------------------------------------------
Enter your target IP address or URL here: localhost
------------------------------------------------------------
Scanning target 127.0.0.1
Time started: 2020-07-22 16:09:47.472806
------------------------------------------------------------
Port 47138 is open
Port 50576 is open
Port scan completed in 0:00:12.724151
------------------------------------------------------------
Threader3000 recommends the following Nmap scan:
************************************************************
nmap -p47138,50576 -sV -sC -T4 -Pn -oA localhost localhost
************************************************************
Would you like to run Nmap or quit to terminal?
------------------------------------------------------------
1 = Run suggested Nmap scan
2 = Run another Threader3000 scan
3 = Exit to terminal
------------------------------------------------------------
Option Selection: 1
nmap -p47138,50576 -sV -sC -Pn -T4 -oA localhost localhost
Starting Nmap 7.80 ( https://nmap.org ) at 2020-07-22 16:10 EDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000029s latency).

PORT      STATE  SERVICE VERSION
47138/tcp closed unknown
50576/tcp closed unknown

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 0.50 seconds
------------------------------------------------------------
Combined scan completed in 0:00:17.416269
Press enter to quit...

------------------------------------------------------------
        Threader 3000 - Multi-threaded Port Scanner          
                       Version 1.0.6                    
                   A project by The Mayor               
------------------------------------------------------------
Enter your target IP address or URL here: 
------------------------------------------------------------
Scanning target 0.0.0.0
Time started: 2020-07-22 16:11:26.873152
------------------------------------------------------------
Port 33298 is open
Port 50238 is open
Port 55576 is open
Port 57460 is open
Port 60176 is open
Port scan completed in 0:00:11.690164
------------------------------------------------------------
Threader3000 recommends the following Nmap scan:
************************************************************
nmap -p33298,50238,55576,57460,60176 -sV -sC -T4 -Pn -oA  
************************************************************
Would you like to run Nmap or quit to terminal?
------------------------------------------------------------
1 = Run suggested Nmap scan
2 = Run another Threader3000 scan
3 = Exit to terminal
------------------------------------------------------------
Option Selection: 1
nmap -p33298,50238,55576,57460,60176 -sV -sC -Pn -T4 -oA  
Traceback (most recent call last):
  File "/usr/local/bin/threader3000", line 8, in <module>
    sys.exit(main())
  File "/usr/local/bin/threader3000.py", line 131, in main
    automate()
  File "/usr/local/bin/threader3000.py", line 110, in automate
    os.mkdir(target)
FileNotFoundError: [Errno 2] No such file or directory: ''
